name: covid19_statistics
description: Estatísticas do COVID-19 no Brasil.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter
  cupertino_icons: ^0.1.2

  # Pub
  dio: ^3.0.9
  mobx: ^1.0.2+2
  flutter_mobx: ^1.0.1
  find_dropdown: ^0.1.8
  intl: ^0.16.0
  flutter_launcher_icons: ^0.7.4

dependency_overrides:
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.0
  mobx_codegen: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - images/background.jpg

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/icon.png"
